# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-08 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('1', 'Male'), ('0', 'Female')], max_length=1)),
                ('age', models.IntegerField()),
                ('restbp', models.IntegerField()),
                ('chol', models.IntegerField()),
                ('durationexercise', models.IntegerField()),
                ('maxHeartRate', models.IntegerField()),
            ],
        ),
    ]
