# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-08 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='diabSymp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insulinDose', models.IntegerField()),
                ('prebreakfastglucose', models.IntegerField()),
                ('postbreakfastglucose', models.IntegerField()),
                ('exerciseactivity', models.IntegerField()),
                ('specialEvent', models.CharField(max_length=100)),
            ],
        ),
    ]
