# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 23:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_diabsymp'),
    ]

    operations = [
        migrations.CreateModel(
            name='cropModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=200)),
                ('devId', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.DeleteModel(
            name='diabSymp',
        ),
        migrations.DeleteModel(
            name='symptoms',
        ),
    ]
